# Generated by Django 5.1.4 on 2026-05-02 10:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('order_submitted', 'Order Submitted'), ('order_assigned', 'Order Assigned'), ('order_pickup', 'Order Pickup'), ('order_completed', 'Order Completed'), ('order_cancelled', 'Order Cancelled'), ('subscription_new', 'New Subscription'), ('subscription_cancelled', 'Subscription Cancelled'), ('payment_failed', 'Payment Failed'), ('driver_application', 'Driver Application'), ('driver_approved', 'Driver Approved'), ('driver_rejected', 'Driver Rejected'), ('rating', 'Rating Left'), ('user_suspended', 'User Suspended')], db_index=True, max_length=40)),
                ('message', models.CharField(max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, help_text='The user whose action triggered this event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_emitted', to=settings.AUTH_USER_MODEL)),
                ('target_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_entries', to='service_requests.servicerequest')),
            ],
            options={
                'db_table': 'activity_activitylog',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['type', '-created_at'], name='activity_ac_type_65f837_idx')],
            },
        ),
    ]
