# Generated by Django 5.1.4 on 2026-07-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_last_active_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_services',
            field=models.JSONField(blank=True, default=list, help_text="Service types the client expects to use most, e.g. ['grocery']."),
        ),
    ]
