# Generated by Django 5.1.4 on 2026-05-02 10:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_type', models.CharField(choices=[('grocery', 'Grocery Pickup'), ('pharmacy', 'Pharmacy Pickup'), ('dry_cleaning', 'Dry Cleaning'), ('package', 'Package Drop-off'), ('retail_return', 'Retail Return'), ('food_pickup', 'Food Pickup')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('pickup_location', models.CharField(max_length=500)),
                ('dropoff_location', models.CharField(max_length=500)),
                ('urgency', models.CharField(choices=[('asap', 'ASAP'), ('today', 'Today'), ('scheduled', 'Scheduled')], db_index=True, default='asap', max_length=20)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('scheduled_window', models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], max_length=20, null=True)),
                ('special_instructions', models.TextField(blank=True, default='')),
                ('estimated_budget', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], db_index=True, default='submitted', max_length=20)),
                ('cancel_reason', models.TextField(blank=True, default='')),
                ('completion_notes', models.TextField(blank=True, default='')),
                ('proof_image_url', models.URLField(blank=True, default='', max_length=500)),
                ('tip_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('tip_stripe_payment_id', models.CharField(blank=True, default='', max_length=255)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='requests_submitted', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, limit_choices_to={'role': 'driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_assigned', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(blank=True, limit_choices_to={'role': 'operator'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'requests_servicerequest',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, choices=[('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], max_length=20, null=True)),
                ('to_status', models.CharField(choices=[('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='service_requests.servicerequest')),
            ],
            options={
                'verbose_name_plural': 'Status history',
                'db_table': 'requests_statushistory',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['status', '-created_at'], name='requests_se_status_75333b_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['client', '-created_at'], name='requests_se_client__1c0fd2_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['driver', 'status'], name='requests_se_driver__5bdf3d_idx'),
        ),
    ]
