# Generated by Django 5.1.4 on 2026-05-02 10:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0.2, help_text="Operator's cut of territory revenue, e.g. 0.20 = 20%", max_digits=4)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(blank=True, limit_choices_to={'role': 'operator'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operated_territory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Territories',
                'db_table': 'territories_territory',
                'ordering': ['name'],
            },
        ),
    ]
