# Generated by Django 5.1.4 on 2026-07-23 17:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='territory',
            name='zip_codes',
            field=models.JSONField(blank=True, default=list, help_text="List of served ZIP codes, e.g. ['92618', '92660']."),
        ),
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('zip_code', models.CharField(blank=True, default='', max_length=12)),
                ('full_name', models.CharField(blank=True, default='', max_length=150)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name_plural': 'Waitlist entries',
                'db_table': 'territories_waitlistentry',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('email', 'zip_code'), name='unique_waitlist_email_zip')],
            },
        ),
    ]
